Repository sequentech/ballot-box, pull requests merged in 2023-02, with the labels that each got.

#156 print errors to log when there is an error calculating the results, and return the error too
  app/controllers/ElectionsApi.scala
Labels: bug

#147 adding extended support for rigid, open and loosely bound lists
  app/models/Models.scala
Labels: enhancement, breaking-change

#158 Adding extended support for rigid, open and loosely bound lists
  app/models/Models.scala
Labels: enhancement, breaking-change

#159 Add support for warn-invalid-implicit-and-explicit (#157)
  app/models/Models.scala
Labels: enhancement
