Repository sequentech/ballot-box, pull requests merged in 2023-06, with the labels that each got.

#167 Bump requests from 2.20.0 to 2.31.0 in /admin (#166)
  admin/requirements.txt
Labels: dependencies

#168 ✨ Countdown until logout
  app/models/Models.scala
Labels: enhancement, breaking-change

#169 ✨different responses on timeout in voting booth
  app/controllers/BallotboxApi.scala
  app/controllers/ElectionsApi.scala
  app/utils/Actions.scala
  app/utils/Response.scala
Labels: enhancement
